# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='static/upload')),
            ],
            options={
                'verbose_name_plural': 'image',
                'verbose_name': 'image',
            },
        ),
    ]
